apiVersion: database.platform.ohanyere.io/v1alpha1
kind: PostgreSQLClaim
metadata:
  name: docker-workflow-api-postgres
  labels:
    app.kubernetes.io/name: docker-workflow-api
    finops.ohanyere.io/cost-center: platform-engineering
spec:
  environment: dev
  databaseName: docker-workflow-api
  size: small
  version: "16"
  backup:
    enabled: true
    retentionDays: 14
