apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: docker-workflow-api
  labels:
    app.kubernetes.io/name: docker-workflow-api
spec:
  host: docker-workflow-api
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 100
