apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-workflow-api
  labels:
    app.kubernetes.io/name: docker-workflow-api
    finops.ohanyere.io/cost-center: platform-engineering
automountServiceAccountToken: false
